/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Penilaian;

/**
 *
 * @author Mutiara
 */
public class GUI_MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public GUI_MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        guiMhs = new javax.swing.JMenuItem();
        guiMK = new javax.swing.JMenuItem();
        guiNilai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setText("PROGRAM PENILAIAN MATA KULIAH");

        jMenuBar1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        guiMhs.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        guiMhs.setText("GUI Mahasiswa");
        guiMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiMhsActionPerformed(evt);
            }
        });
        jMenu2.add(guiMhs);

        guiMK.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        guiMK.setText("GUI Mata Kuliah");
        guiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiMKActionPerformed(evt);
            }
        });
        jMenu2.add(guiMK);

        guiNilai.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        guiNilai.setText("GUI Penilaian");
        guiNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiNilaiActionPerformed(evt);
            }
        });
        jMenu2.add(guiNilai);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiMhsActionPerformed
        // TODO add your handling code here:
        GUI_Mahasiswa1 mhs = new GUI_Mahasiswa1();
        mhs.show();
        this.dispose();

    }//GEN-LAST:event_guiMhsActionPerformed

    private void guiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiMKActionPerformed
        // TODO add your handling code here:
        GUI_Matkul1 mk = new GUI_Matkul1();
        mk.show();
        this.dispose();
    }//GEN-LAST:event_guiMKActionPerformed

    private void guiNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiNilaiActionPerformed
        // TODO add your handling code here:
        GUI_Nilai nilai = new GUI_Nilai();
        nilai.show();
        this.dispose();
    }//GEN-LAST:event_guiNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem guiMK;
    private javax.swing.JMenuItem guiMhs;
    private javax.swing.JMenuItem guiNilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
