/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Penilaian;

/**
 *
 * @author Mutiara
 */
public class GUI_Nilai extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Nilai
     */
    public GUI_Nilai() {
        initComponents();
        txtNP.setEnabled(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKodeMK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoNilai = new javax.swing.JTextArea();
        txtNT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNP = new javax.swing.JTextField();
        cek_prak = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtKodeMK.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("PROGRAM PENILAIAN");

        btnNA.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        btnNA.setText("Hasil Nilai Akhir");
        btnNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAActionPerformed(evt);
            }
        });

        memoNilai.setEditable(false);
        memoNilai.setColumns(20);
        memoNilai.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        memoNilai.setRows(5);
        jScrollPane1.setViewportView(memoNilai);

        txtNT.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel4.setText("Nilai Tugas");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel3.setText("Kode MK");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel2.setText("NIM");

        txtNIM.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel5.setText("Nilai Praktikum");

        txtNP.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        cek_prak.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        cek_prak.setText("Praktikum");
        cek_prak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cek_prakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(86, 86, 86))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cek_prak))
                                .addComponent(txtNT, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNP, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cek_prak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnNA)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAActionPerformed
        // TODO add your handling code here:
        memoNilai.setText("");
Penilaian nilai; // instansiasi
       
//objek nilai dari super class diinisiaalisasi dengan sub class
nilai = new Penilaian_NonPrak(); 
       
nilai.NIM = txtNIM.getText();
nilai.kode_mk = txtKodeMK.getText();    
       
if (cek_prak.isSelected()){
   nilai.nilaiTugas = Integer.parseInt(txtNT.getText());
   nilai.nilaiPrak = Integer.parseInt(txtNP.getText());
   memoNilai.append("Nilai Akhir Mata Kuliah \n");
   memoNilai.append("--------------------------------------\n");
   memoNilai.append("NIM                : "+nilai.NIM +"\n");
   memoNilai.append("Kode MK           : "+nilai.kode_mk +"\n");
   memoNilai.append("Nilai Tugas       : "+nilai.nilaiTugas +"\n");
   memoNilai.append("Nilai Praktikum    : "+nilai.nilaiPrak +"\n");
   memoNilai.append("--------------------------------------\n");
   memoNilai.append("Nilai Akhir      : "+nilai.tampilNA());
}else {
   nilai.nilaiTugas = Integer.parseInt(txtNT.getText());
   memoNilai.append("Nilai Akhir Mata Kuliah \n");
   memoNilai.append("--------------------------------------\n");
   memoNilai.append("NIM             : "+nilai.NIM +"\n");
   memoNilai.append("Kode MK         : "+nilai.kode_mk +"\n");
   memoNilai.append("Nilai Tugas     : "+nilai.nilaiTugas +"\n");
   memoNilai.append("--------------------------------------\n");
   memoNilai.append("Nilai Akhir      : "+nilai.nilaiAkhir());
}        

       /* memoNilai.setText("");
       Penilaian nilai; // instansiasi
       
       //objek nilai dari super class diinisiaalisasi dengan sub class
       nilai = new Penilaian_NonPrak(); 
       
       nilai.NIM = txtNIM.getText();
       nilai.kode_mk = txtKodeMK.getText();    
       
       if (cek_prak.isSelected()){
           nilai.nilaiTugas = Integer.parseInt(txtNT.getText());
           nilai.nilaiPrak = Integer.parseInt(txtNP.getText());
           memoNilai.append("Nilai Akhir Mata Kuliah \n");
           memoNilai.append("--------------------------------------\n");
           memoNilai.append("NIM                : "+nilai.NIM +"\n");
           memoNilai.append("Kode MK           : "+nilai.kode_mk +"\n");
           memoNilai.append("Nilai Tugas       : "+nilai.nilaiTugas +"\n");
           memoNilai.append("Nilai Praktikum    : "+nilai.nilaiPrak +"\n");
           memoNilai.append("--------------------------------------\n");
           memoNilai.append("Nilai Akhir      : "+nilai.tampilNA());
           
       }else {
           nilai.nilaiTugas = Integer.parseInt(txtNT.getText());
           memoNilai.append("Nilai Akhir Mata Kuliah \n");
           memoNilai.append("--------------------------------------\n");
           memoNilai.append("NIM             : "+nilai.NIM +"\n");
           memoNilai.append("Kode MK         : "+nilai.kode_mk +"\n");
           memoNilai.append("Nilai Tugas     : "+nilai.nilaiTugas +"\n");
           memoNilai.append("--------------------------------------\n");
           memoNilai.append("Nilai Akhir      : "+nilai.nilaiAkhir());
       }*/
        
    }//GEN-LAST:event_btnNAActionPerformed

    private void cek_prakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cek_prakActionPerformed
        // TODO add your handling code here:
        if (cek_prak.isSelected()){
            txtNP.setEnabled(true);
        }
        else{
            txtNP.setEnabled(false);
        }
    }//GEN-LAST:event_cek_prakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Nilai().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNA;
    private javax.swing.JCheckBox cek_prak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memoNilai;
    private javax.swing.JTextField txtKodeMK;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNP;
    private javax.swing.JTextField txtNT;
    // End of variables declaration//GEN-END:variables
}
