/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan_1818071;

/**
 *
 * @author Kunkka
 */
public class GUI_HotWheels extends javax.swing.JFrame {

    /**
     * Creates new form GUI_HotWheels
     */
    public GUI_HotWheels() {
        initComponents();
        /*HotWheels buyer = new HotWheels();
        txt_nama.setText("Alif Fatoni");
        txt_nama.setEnabled(false);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        radiobtnPerempuan = new javax.swing.JRadioButton();
        radiobtnLaki = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txt_bayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_uang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_kembali = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_id1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Avery HotWheels Store");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 274, 40);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel2.setText("ID Buyer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 48, 17);

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 34, 17);

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 74, 17);

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel5.setText("Apakah Member?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 120, 20);

        txt_id.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(txt_id);
        txt_id.setBounds(540, 30, 110, 23);

        txt_nama.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(txt_nama);
        txt_nama.setBounds(130, 110, 146, 23);

        txt_alamat.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(txt_alamat);
        txt_alamat.setBounds(130, 200, 146, 23);

        jButton1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 30, 80, 25);

        radiobtnPerempuan.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        radiobtnPerempuan.setForeground(new java.awt.Color(255, 51, 51));
        radiobtnPerempuan.setText("Perempuan");
        getContentPane().add(radiobtnPerempuan);
        radiobtnPerempuan.setBounds(180, 160, 93, 23);

        radiobtnLaki.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        radiobtnLaki.setForeground(new java.awt.Color(51, 51, 255));
        radiobtnLaki.setText("Pria");
        getContentPane().add(radiobtnLaki);
        radiobtnLaki.setBounds(130, 160, 47, 25);

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 40, 17);

        jCheckBox1.setText("Ya");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(190, 250, 81, 23);

        txt_bayar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(txt_bayar);
        txt_bayar.setBounds(130, 280, 146, 23);

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel7.setText("Total Bayar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 290, 100, 17);

        txt_uang.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(txt_uang);
        txt_uang.setBounds(130, 320, 146, 23);

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel8.setText("Uang Diterima");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 330, 100, 17);

        txt_kembali.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(txt_kembali);
        txt_kembali.setBounds(130, 360, 146, 23);

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel9.setText("Kembali");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 370, 100, 17);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Buyer", "Nama", "Jenis Kelamin", "Alamat", "Keanggotaan", "Total Bayar"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(290, 60, 450, 270);

        jButton2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 360, 90, 25);

        jButton3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 360, 90, 25);

        txt_id1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(txt_id1);
        txt_id1.setBounds(130, 60, 146, 23);

        jButton4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(520, 360, 90, 25);

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Mengosongkan memoKTM
       

        // Implementasi uang diterima, kembalian, dan menampilkan pada memoKTM
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_HotWheels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_HotWheels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_HotWheels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_HotWheels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_HotWheels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radiobtnLaki;
    private javax.swing.JRadioButton radiobtnPerempuan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_uang;
    // End of variables declaration//GEN-END:variables
}
